"""Shared label utilities for Path-* training scripts."""

NEW_LABEL_MAPPING = {
    "Malignant": "Epithelial_Malignant",
    "Tumor Cells": "Epithelial_Malignant",
    "Proliferative Tumor Cells": "Epithelial_Malignant",
    "VEGFA+ Tumor Cells": "Epithelial_Malignant",
    "Inflammatory Tumor Cells": "Epithelial_Malignant",
    "SOX2-OT+ Tumor Cells": "Epithelial_Malignant",
    "Malignant Cells Lining Cyst": "Epithelial_Malignant",
    "CFTR- Tumor Cells": "Epithelial_Malignant",
    "Tumor_epithelial": "Epithelial_Malignant",
    "Metaplastic Cells": "Epithelial_Malignant",
    "Airway_epithelium": "Epithelial_Airway",
    "Ciliated Epithelial Cells": "Epithelial_Airway",
    "Alveolar": "Epithelial_Alveolar",
    "Ductal": "Ductal",
    "Acinar": "Acinar",
    "Endocrine 1": "Endocrine",
    "Endocrine 2": "Endocrine",
    "Fallopian Tube Epithelium": "Epithelial_Fallopian",
    "Endothelial": "Endothelial",
    "Endothelial Cell": "Endothelial",
    "Stromal Associated Endothelial Cells": "Endothelial",
    "Lymphatic Endothelial Cells": "Endothelial",
    "Tumor_Associated_Endothelial": "Endothelial_TumorAssociated",
    "Tumor Associated Endothelial Cells": "Endothelial_TumorAssociated",
    "Fibroblast": "Fibroblast",
    "Fibroblasts": "Fibroblast",
    "Stromal Cell": "Fibroblast",
    "Stromal Associated Fibroblasts": "Tumor_Associated_Fibroblast",
    "Tumor Associated Fibroblasts": "Tumor_Associated_Fibroblast",
    "Fibroblast/CAF": "Tumor_Associated_Fibroblast",
    "Fibroblast_PDGFRA_CAF": "Tumor_Associated_Fibroblast",
    "Tumor_Associated_Fibroblast": "Tumor_Associated_Fibroblast",
    "Smooth Muscle Cells": "Smooth_Muscle",
    "Smooth_Muscle": "Smooth_Muscle",
    "Pericytes": "Pericyte",
    "Cardiomyocyte": "Cardiomyocyte",
    "T Cells": "T_Cell",
    "T Cell": "T_Cell",
    "T_cells": "T_Cell",
    "Regulatory T Cell": "T_Cell",
    "Effector CD4+ αβ T Cell": "T_Cell",
    "Effector CD8+ αβ T Cell": "T_Cell",
    "CD4+ αβ Memory T Cell": "T_Cell",
    "CD8+ αβ Memory T Cell": "T_Cell",
    "Naive Thymus Derived CD4+ αβ T Cell": "T_Cell",
    "Mature NK T Cell": "T_Cell",
    "Type I NK T Cell": "T_Cell",
    "NK Cell": "NK_Cell",
    "NK Cells": "NK_Cell",
    "B Cell": "B_Cell",
    "B Cells": "B_Cell",
    "B_lineage": "B_Cell",
    "Naive B Cell": "B_Cell",
    "Memory B Cell": "B_Cell",
    "Plasma Cell": "Plasma_Cell",
    "Macrophages": "Macrophage",
    "Macrophage": "Macrophage",
    "Intermediate Monocyte": "Monocyte",
    "Classical Monocyte": "Monocyte",
    "Non Classical Monocyte": "Monocyte",
    "Neutrophil": "Neutrophil",
    "Plasmacytoid Dendritic Cell": "Dendritic_Cell",
    "CD141+ Myeloid Dendritic Cell": "Dendritic_Cell",
    "CD1c+ Myeloid Dendritic Cell": "Dendritic_Cell",
    "Mature Conventional Dendritic Cell": "Dendritic_Cell",
    "Mast Cells": "Mast_Cell",
    "Mast_Cell": "Mast_Cell",
}

CLASSES_TO_REMOVE = [
    "Fallopian Tube Epithelium",
    "Epithelial_Fallopian",
    "Pericyte",
    "Pericytes",
    "Unassigned",
    "Ambiguous/Low_confidence",
    "Myeloid",
    "T and NK Cells",
    "CXCL9/10 Cells",
    "SMC/Pericyte",
    "Granulosa Cells",
    "Erythrocyte",
    "Hematopoietic Stem Cell",
    "Hematopoietic_Stem_Cell",
]

